name: Notify flake

on:
  push:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: gabrycina/redazione-flake
          event-type: deploy
